{% set name = "libnvtiff" %}
{% set version = "0.6.0.78" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type=="sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set platform = "windows-x86_64" %}  # [win64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: libnvtiff-split
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
{% set cuda_major = environ.get("cuda_compiler_version", "13.0").split(".")[0] %}

{% set sha256 = "2c889bf4767e4ab8e81f46e9f2b675e1d424c46e4a54bb97049bbb3b87ff4aed" %}  # [linux64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "8018c8dcff3bcac9f0e74827d312f67169b9fd01b40b2bbb431dd9bf8a5c38aa" %}  # [linux64 and (cuda_compiler_version or "").startswith("13")]
{% set sha256 = "3694b154003a3741b68fc9ff70ad9195a756be1feb2404be6f2482bb97574c00" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
{% set sha256 = "a0667c222c41186b9bf4fbc447281375bd83ec4b4c6658c37440149b78df4f41" %}  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
{% set sha256 = "1c1707880f6438dee0fcf58ab2cc62125e8140c90a983029ef6186aa7a8dc798" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]
{% set sha256 = "1eb6848921808f28d703320f52ac584743a365d9bef4b105482db2d63e01f039" %}  # [win64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "8a99af1fd4919fe21829bf05e3e4b87aa2adb563e409a86ee54d2746f01f0045" %}  # [win64 and (cuda_compiler_version or "").startswith("13")]

source:
  - url: https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/{{ platform }}/libnvtiff-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
    sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or ppc64le or cuda_compiler_version in (None, "None")]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:

  - name: libnvtiff{{ version.split(".")[0] }}
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvtiff.so.*            # [linux]
      - Library\bin\nvtiff*.dll       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvtiff.so.{{ version.split(".")[0] }}                            # [linux]
        - test -f $PREFIX/lib/libnvtiff.so.{{ version }}                                          # [linux]
        - if not exist %LIBRARY_BIN%\nvtiff_{{ version.split(".")[0] }}.dll exit 1              # [win]
    about:
      summary: The NVIDIA nvTIFF runtime library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install libnvtiff-dev to build
        with nvTIFF.

  - name: libnvtiff
    requirements:
      run:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], max_pin="x.x.x") }}
    about:
      summary: The NVIDIA nvTIFF runtime library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install libnvtiff-dev to build
        with nvTIFF.

  - name: libnvtiff-dev
    build:
      run_exports:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], max_pin="x.x.x") }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
    files:
      - lib/libnvtiff.so                                  # [linux]
      # - lib/pkgconfig/nvtiff*.pc                          # [linux]
      - include/nvtiff*                                   # [linux]
      - Library\include                                   # [win]
      - Library\lib\nvtiff.lib                            # [win]
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], exact=True) }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
      run:
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], exact=True) }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvtiff.so                                    # [linux]
        # - test -f $PREFIX/lib/pkgconfig/nvtiff*.pc                            # [linux]
        - test -f $PREFIX/include/nvtiff_version.h                            # [linux]
        - test -f $PREFIX/include/nvtiff.h                                    # [linux]
        - if not exist %LIBRARY_INC%\nvtiff_version.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\nvtiff.h exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\nvtiff.lib exit 1                        # [win]

  - name: libnvtiff-static
    build:
      skip: True  # [not linux]
    files:
      - lib/libnvtiff_static.a  # [linux]
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libnvtiff-dev", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libnvtiff_static.a  # [linux]
    about:
      summary: The NVIDIA nvTIFF static library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a developer package only. Developers should install this package to link
        statically to nvTIFF.

about:
  home: https://docs.nvidia.com/cuda/nvtiff/
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: The NVIDIA nvTIFF development package.
  description: >-
    nvTIFF is a GPU accelerated TIFF(Tagged Image File Format) encode/decode library built
    on the CUDA platform. The library is supported on Volta+ GPU architectures.
  doc_url: https://docs.nvidia.com/cuda/nvtiff/

extra:
  recipe-maintainers:
    - conda-forge/cuda
